import { SidebarLink } from "@/types";

export const sidebarLinks: SidebarLink[] = [
  {
    route: "/orders",
    label: "ORDERS",
    authorized: ["MANAGER", "TÉCNICO", "LIDER"],
  },
  {
    route: "/",
    label: "SERVICES",
    authorized: ["ADMIN"],
  },
  {
    route: "/",
    label: "SERVICES",
    authorized: ["MANAGER", "TÉCNICO", "LIDER"],
  },
  {
    route: "/",
    label: "CLIENTS",
    authorized: ["MANAGER", "LIDER", "ADMIN"],
  },
  {
    route: "/",
    label: "LOCATIONS",
    authorized: ["ADMIN", "CONTABILIDAD"],
  },
  {
    route: "/",
    label: "DASHBOARD",
    authorized: ["MANAGER", "LIDER", "ADMIN", "CONTABILIDAD"],
  },
  {
    route: "/",
    label: "DASHBOARD BAYS",
    authorized: ["MANAGER", "ADMIN", "CONTABILIDAD", "LIDER"],
  },
  {
    route: "/location-selector",
    label: "LOCATION SELECTOR",
    authorized: ["MANAGER", "TÉCNICO", "LIDER"],
  },
];

export const carMakeOptions = [
  { value: "Acura", label: "Acura" },
  { value: "Alfa-Romeo", label: "Alfa-Romeo" },
  { value: "Aston-Martin", label: "Aston-Martin" },
  { value: "Audi", label: "Audi" },
  { value: "Bentley", label: "Bentley" },
  { value: "BMW", label: "BMW" },
  { value: "Bugatti", label: "Bugatti" },
  { value: "Buick", label: "Buick" },
  { value: "Cadillac", label: "Cadillac" },
  { value: "Canoo", label: "Canoo" },
  { value: "Chevrolet", label: "Chevrolet" },
  { value: "Chrysler", label: "Chrysler" },
  { value: "Citroen", label: "Citroen" },
  { value: "Daewoo", label: "Daewoo" },
  { value: "Dodge", label: "Dodge" },
  { value: "Ferrari", label: "Ferrari" },
  { value: "Fiat", label: "Fiat" },
  { value: "Ford", label: "Ford" },
  { value: "Genesis", label: "Genesis" },
  { value: "GMC", label: "GMC" },
  { value: "Honda", label: "Honda" },
  { value: "Hummer", label: "Hummer" },
  { value: "Hyundai", label: "Hyundai" },
  { value: "Infiniti", label: "Infiniti" },
  { value: "Jaguar", label: "Jaguar" },
  { value: "Jeep", label: "Jeep" },
  { value: "Kia", label: "Kia" },
  { value: "Lamborghini", label: "Lamborghini" },
  { value: "Land-Rover", label: "Land-Rover" },
  { value: "Lexus", label: "Lexus" },
  { value: "Lincoln", label: "Lincoln" },
  { value: "Lotus", label: "Lotus" },
  { value: "Lucid", label: "Lucid" },
  { value: "Maserati", label: "Maserati" },
  { value: "Mazda", label: "Mazda" },
  { value: "McLaren", label: "McLaren" },
  { value: "Mercedes-Benz", label: "Mercedes-Benz" },
  { value: "MG", label: "MG" },
  { value: "Mini", label: "Mini" },
  { value: "Mitsubishi", label: "Mitsubishi" },
  { value: "Nissan", label: "Nissan" },
  { value: "Oldsmobile", label: "Oldsmobile" },
  { value: "Peugeot", label: "Peugeot" },
  { value: "Polestar", label: "Polestar" },
  { value: "Pontiac", label: "Pontiac" },
  { value: "Porsche", label: "Porsche" },
  { value: "RAM", label: "RAM" },
  { value: "Renault", label: "Renault" },
  { value: "Rivian", label: "Rivian" },
  { value: "Rolls-Royce", label: "Rolls-Royce" },
  { value: "SCION", label: "SCION" },
  { value: "SEAT", label: "SEAT" },
  { value: "Subaru", label: "Subaru" },
  { value: "Suzuki", label: "Suzuki" },
  { value: "Tesla", label: "Tesla" },
  { value: "Toyota", label: "Toyota" },
  { value: "Volkswagen", label: "Volkswagen" },
  { value: "Volvo", label: "Volvo" },
];

export const carColorsOptions = [
  { value: "black", label: "Black", color: "#000" },
  { value: "purple", label: "Purple", color: "#5243AA" },
  { value: "silver", label: "Silver", color: "#666666" },
  { value: "grey", label: "Grey", color: "#808080" },
  { value: "white", label: "White", color: "#fff" },
  { value: "blue", label: "Blue", color: "#0052CC" },
  { value: "red", label: "Red", color: "#FF5630" },
  { value: "brown", label: "Brown", color: "#835C3B" },
  { value: "green", label: "Green", color: "#36B37E" },
  { value: "orange", label: "Orange", color: "#FF8B00" },
  { value: "yellow", label: "Yellow", color: "#FFC400" },
];

export const carTypes = [
  { value: "1", label: "SEDAN" },
  { value: "2", label: "SUV" },
  { value: "3", label: "LARGE" },
  { value: "4", label: "VAN OR TRUCK" },
  { value: "5", label: "MOTORCYCLE" },
];
